const $=id=>document.getElementById(id);let cfg=null,sha=null;
function say(text,kind=''){const e=$('message');e.textContent=text;e.className=kind}
function headers(){return {Accept:'application/vnd.github+json',Authorization:`Bearer ${$('token').value.trim()}`,'X-GitHub-Api-Version':'2022-11-28'}}
function apiPath(){return `https://api.github.com/repos/${$('repo').value.trim()}/contents/${$('path').value.trim()}`}
function decode(b64){const bytes=Uint8Array.from(atob(b64.replace(/\n/g,'')),c=>c.charCodeAt(0));return new TextDecoder().decode(bytes)}
function encode(text){const bytes=new TextEncoder().encode(text);let s='';for(const b of bytes)s+=String.fromCharCode(b);return btoa(s)}
function render(){const box=$('products');box.innerHTML='';cfg.products.forEach((p,i)=>{const d=document.createElement('div');d.className='product';d.innerHTML=`<label>Nombre<input data-i="${i}" data-k="name" value=""></label><label>URL<input data-i="${i}" data-k="url" value=""></label><button class="remove" data-remove="${i}">Quitar</button>`;d.querySelectorAll('input').forEach(x=>x.value=p[x.dataset.k]||'');box.append(d)});$('editor').classList.remove('hidden')}
$('load').onclick=async()=>{try{if(!$('token').value||!$('repo').value)throw Error('Completá repositorio y token');const r=await fetch(apiPath(),{headers:headers()});if(!r.ok)throw Error(`GitHub respondió ${r.status}`);const j=await r.json();sha=j.sha;cfg=JSON.parse(decode(j.content));cfg.products??=[];render();say('Configuración cargada','ok')}catch(e){say(e.message,'error')}};
$('products').oninput=e=>{if(e.target.dataset.i)cfg.products[+e.target.dataset.i][e.target.dataset.k]=e.target.value};$('products').onclick=e=>{if(e.target.dataset.remove){cfg.products.splice(+e.target.dataset.remove,1);render()}};$('add').onclick=()=>{cfg.products.push({name:'Nuevo producto',url:'https://www.carrefour.com.ar/'});render()};
$('save').onclick=async()=>{try{const content=JSON.stringify(cfg,null,2)+'\n';const r=await fetch(apiPath(),{method:'PUT',headers:{...headers(),'Content-Type':'application/json'},body:JSON.stringify({message:'Actualizar productos del monitor',content:encode(content),sha})});if(!r.ok)throw Error(`No se pudo guardar (${r.status})`);const j=await r.json();sha=j.content.sha;say('Guardado correctamente en GitHub','ok')}catch(e){say(e.message,'error')}};
$('run').onclick=()=>window.open(`https://github.com/${$('repo').value.trim()}/actions/workflows/daily.yml`,'_blank');
